config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :profiles
  resources :countries do
    resources :cities do
      resources :galleries
    end
  end
  root 'countries#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  belongs_to :user
  has_one :gallery, dependent: :destroy

  paperclip_opts = {
      	:styles => { :small => "300x300#", :medium => "1000x600#" }
      }
      if Rails.env.development?
      	paperclip_opts.merge! :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    						  :url => "/system/:attachment/:id/:style/:filename"
      else
      	paperclip_opts.merge! :storage => :s3,
      						  :bucket  => ENV['S3_BUCKET_NAME']
      end 

  has_attached_file :photo, paperclip_opts
  validates :photo, presence: true, :attachment_content_type => { :content_type => ['image/png', 'image/jpg', 'image/jpeg']}
  validates :title, presence: true, uniqueness: true
end

app/models/country.rb
class Country < ActiveRecord::Base
      has_many :cities, dependent: :destroy
      belongs_to :user

      paperclip_opts = {
      	:styles => { :small => "300x300#", :medium => "1000x600#" }
      }
      if Rails.env.development?
      	paperclip_opts.merge! :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    						  :url => "/system/:attachment/:id/:style/:filename"
      else
      	paperclip_opts.merge! :storage => :s3,
      						  :bucket  => ENV['S3_BUCKET_NAME']
      end 

      has_attached_file :photo, paperclip_opts

      validates :photo, presence: true, :attachment_content_type => { :content_type => ['image/png', 'image/jpg', 'image/jpeg']}
      validates :title, presence: true, uniqueness: true

      def title=(s)
      	super s.titleize
      end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :city, :dependent => :destroy
	#belongs_to :user, through: :city
	has_many :gallery_photos
end

app/models/gallery_photo.rb
class GalleryPhoto < ActiveRecord::Base
   belongs_to :gallery 
   paperclip_opts = {
      	:styles => { :small => "300x300#", :medium => "1000x600#" }
      }
      if Rails.env.development?
      	paperclip_opts.merge! :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    						  :url => "/system/:attachment/:id/:style/:filename"
      else
      	paperclip_opts.merge! :storage => :s3,
      						  :bucket  => ENV['S3_BUCKET_NAME']
      end 

  has_attached_file :photo, paperclip_opts
  validates :photo, presence: true, :attachment_content_type => { :content_type => ['image/png', 'image/jpg', 'image/jpeg']}
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	paperclip_opts = {
      	:styles => { :small => "300x300#"}
    }
      if Rails.env.development?
      	paperclip_opts.merge! :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    						  :url => "/system/:attachment/:id/:style/:filename"
      else
      	paperclip_opts.merge! :storage => :s3,
      						  :bucket  => ENV['S3_BUCKET_NAME']
      end


	belongs_to :user
	has_many :countries
	has_many :cities, through: :countries
	has_attached_file :photo, paperclip_opts
	validates :photo, presence: true, :attachment_content_type => { :content_type => ['image/png', 'image/jpg', 'image/jpeg']}
	validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile
  has_many :countries, dependent: :destroy
  has_many :cities, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_filter :require_permission, :except => [:show, :index, :new, :create]

  	def require_permission
    	unless current_user == Country.find(params[:id]).user or current_user.try(:admin?)
          redirect_to root_path
    	end
  	end

	def create
		@country = Country.find(params[:country_id])
		@city = @country.cities.build(city_params)
		@gallery = Gallery.create({:city_id => @city.id})
		@city.gallery = @gallery
		if @city.save
			redirect_to country_path(@country)
		else
			render 'new'
		end
	end

	def new
		@country = Country.find(params[:country_id])
		@city = City.new
	end

	def destroy
		@country = Country.find(params[:country_id])
		@city = @country.cities.find(params[:id])
		@city.destroy
		redirect_to country_path(@country)
	end

	def show
		@city = City.find(params[:id])
	end

	private
		def city_params
			params.require(:city).permit(:title, :photo)
		end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
   
  before_filter :require_permission, :except => [:show, :index, :new, :create]


   def require_permission
    unless current_user == Country.find(params[:id]).user or current_user.try(:admin?)
          redirect_to root_path
    end
  end

   def show
       @country = Country.find(params[:id])
   end

   def create
      @country = Country.new(country_params)
      @country.user = current_user

      if @country.save
        redirect_to @country
      else 
        render 'new'
      end
   end   

   def new
      @country = Country.new
   end

   def index
       @countries = Country.all
   end

   def destroy
       @country = Country.find(params[:id])
       @country.destroy
       redirect_to countries_path
   end

   def update
       @country = Country.find(params[:id])
       
       if @country.update_attributes(country_params)
        redirect_to countries_path
       else 
         render 'edit'
        end
   end

   def edit
      @country = Country.find(params[:id])

   end

   private
	def country_params
	    params.require(:country).permit(:title, :text, :photo)
	end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	def show
		@gallery = Gallery.find(params[:id])
	end

	def edit
		@gallery = Gallery.find(params[:id])
	end

	def update
		@gallery = Gallery.find(params[:id])
		p = @gallery.gallery_photos.build(gallery_params)
		p.save
		render 'show'
	end

	def destroy
		if params[:photo_id]
			GalleryPhoto.delete(params[:photo_id])
		end
		redirect_to 'show'
	end

	private
		def gallery_params
			params.require(:gallery).permit(:photo)
		end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	before_filter :require_permission, :except => [:show, :index, :new, :create]
	after_filter :turn_off

	def turn_off
		@on_profile = false
		@edit_profile = false
	end

	def require_permission
     	unless current_user == Profile.find(params[:id]).user or current_user.try(:admin?)
         	redirect_to root_path
      	end
  	end

	def new
		if current_user
			@profile = Profile.new
	    else
	    	flash[:notice] = "You must log in first."
	    	redirect_to new_user_session_path
	    end
	end


	def create
		@profile = Profile.where(user_id: current_user.id).first
		if @profile
			flash[:notice] = "You already have a profile."
			flash.keep
			redirect_to @profile
		elsif current_user
			@profile = Profile.new(profile_params)
			@profile.user = current_user
			if @profile.save
				redirect_to @profile 
			else
				flash[:notice] = "error in submission"
				render "new"
			end
		else
			redirect_to root_path
		end

	end

	def edit
		@profile = Profile.find(params[:id])
		@edit_profile = true
	end

	def show
		@profile = Profile.find(params[:id])
		@on_profile = true
		unless @profile
			flash[:notice] = "new profile"
			render "new"
		end
	end
   
    def index
    	@profiles = Profile.all
    end

    def destroy
    	@profile = Profile.find(params[:id])
    	@profile.destroy
    	flash[:notice] = "Profile successfully deleted."
    	redirect_to root_path
    end
 	
 	def update
 		@profile = Profile.find(params[:id])
 		if @profile.update_attributes(profile_params)
 			redirect_to profile_path
 		else
 			flash[:notice] = "Error in update."
 			render 'edit'
 		end
 	end

 	private
 	def profile_params
 		params.require(:profile).permit(:name, :photo)
 	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/new.html.erb
<%= stylesheet_link_tag "form", :media => "all" %>

<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>

<div id="topleftbutton">
<%= link_to '', countries_path, id: "back" %>
<%= link_to "Back", countries_path, id: "backtext" %></div>

<%= form_for [@country, @country.cities.build], :html => { :multipart => true } do |f| %>
  <div id="error_explanation">
    <% if @city.errors.any? %>
      <%= pluralize(@city.errors.count, "error") %> prohibited
        this city from being saved:
        <ul>
          <% @city.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
  <div id="container">
    <div id="country_name">
      <%= f.label "New city" %><br>
    </div>
    <%= f.text_field :title, id: "box"%>  
    <div id="upload">
      <%= f.file_field :photo %>
    </div>
    <div id="submit">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/cities/show.html.erb
<% if true %>
	No photos
<% end %>
<% @city.gallery.gallery_photos do |photo| %>

<% end %>
<div id = "hfieow">
fbeuwaifhewuofewhao</div>

app/views/countries/edit.html.erb
<%= stylesheet_link_tag "form" %>

<h1>Editing country</h1>
 
<%= form_for @country, url: country_path(@country) , :html => { :multipart => true }, method: :patch do |f| %>
 
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@country.errors.count, "error") %> prohibited
        this submission from being saved:
      </h2>
      <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label "Name of country" %><br>
    <%= f.text_field :title %>
  </p>
 

  <%= f.file_field :photo %>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<%= javascript_include_tag "index" %>
<%= stylesheet_link_tag "index", :media => "all" %>

<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>

<% if current_user %>
  <div id="new_button">
    <%= link_to '', new_country_path, id: "new_button_background" %> 
    <%= link_to '+', new_country_path, id: "new_button_text" %>
  </div>
<% end %>


<div id="title">Countries</div>

<div id="cont">
  <% @countries.each do |country| %>
      <div id="each">
      <div id="countryname">
        <%= link_to country.title, country_path(country), id: "title_text" %></div>
      <div id="overlaywrapper">
        <%= link_to " ", country_path(country), id: "pic_overlay" %>
      </div>
      <div id="pic_container">
      <div id="pic_cropper">
      <div id="pic">
      <%= link_to( image_tag(country.photo.url(:medium)), country_path(country) ) %></div></div></div>
      <div id="ed">
      <% if current_user == country.user or current_user.try(:admin?) == true %>
        <div id="editer">

        <%= link_to(  image_tag('edit.png'), edit_country_path(country), id: "icon") %></div>
      
      <div id="line"> | </div> 
      <div id="deleter">
      <%= link_to image_tag('delete.png'), country_path(country), method: :delete, id: "icon" %></div>

      <% end %>
     </div>
      </div>
    </div>

  <% end %>

app/views/countries/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>

<%= stylesheet_link_tag "form" %>

<div id="topleftbutton">
<%= link_to '', countries_path, id: "back" %>
<%= link_to "Back", countries_path, id: "backtext" %></div>


<%= form_for :country, url: countries_path, :html => { id: "form_id", :multipart => true } do |f| %>
  <div id="error_explanation">
    <% if @country.errors.any? %>
      <%= pluralize(@country.errors.count, "error") %> prohibited
        this country from being saved:
        <ul>
          <% @country.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
  <div id="container">
    <div id="country_name">
      <%= f.label "New country" %><br>
    </div>
    <%= f.text_field :title, id: "box"%>  
    <div id="upload">
      <%= f.file_field :photo %>
    </div>
    <div id="submit">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/countries/show.html.erb
<%= stylesheet_link_tag "show", :media => "all" %>

<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>

<div id="back_overlay"></div>

<div id="topleftbutton">
    <%= link_to '', countries_path, id: "back" %>
    <%= link_to "Back", countries_path, id: "backtext" %>
</div>

<div id="title">
    <%= @country.title %>
</div>

<% if current_user == @country.user %>
  <div id="new_button">
    <%= link_to '', new_country_city_path(@country), id: "new_button_background" %> 
    <%= link_to '+', new_country_city_path(@country), id: "new_button_text" %>
  </div>
<% end %>


<div id="container">
    <div id="city_boxes" >
        <% @country.cities.each do |city| %>
            <div id="window_container">
                <%= link_to " ", country_city_gallery_path(@country, city.id, city.gallery), id: "window_overlay" %>
                <div id="city_title">
                    <%= city.title %>
                </div>
                <div id="window">
                    <div id="circle_div">
                        <%= image_tag city.photo.url(:medium), id: "circle" %></div>
                        <%= link_to '', [city.country, city], method: :show %>
                </div>
                <% if current_user == @country.user or current_user.try(:admin?) %>
                    <div id="links">
                        <div id="delete_div">
                            <%= link_to 'Delete', [city.country, city], method: :delete, id: "delete_text" %>
                        </div>   
                    </div>  
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/galleries/edit.html.erb
<div id="container">

  	<% @gallery.gallery_photos.each do |gphoto| %>
    	<%= image_tag gphoto.photo.url(:small)%>
    	<div id="delete_div">
    </div>   
  <% end %>
  	<%= form_for [@gallery.city.country, @gallery.city, @gallery], url: {action: 'update'} do |f| %>
		<div class = "upload">
			<%= f.file_field :photo %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>

</div>

app/views/galleries/show.html.erb
<% if current_user == @gallery.city.country.user %>
  <div id="new_button">
    <%= link_to '', edit_country_city_gallery_path(@gallery.city.country, @gallery.city, @gallery), id: "new_button_background" %> 
    <%= link_to '+',edit_country_city_gallery_path(@gallery.city.country, @gallery.city, @gallery), id: "new_button_text" %>
  </div>
<% end %>


<div class="thumbs">
	<% @gallery.gallery_photos.each do |gphoto| %>
		<a href="<%= gphoto.photo.url%>", style="background-image:url(<%= gphoto.photo.url%>)">
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="navbar"></div>
<% unless current_user %>
    <div class="log">
      <%= link_to "", new_user_session_path, id: "stuff" %>
      <%= link_to "Login", new_user_session_path, :class => "log_text" %>
    </div>
<% else %>
  <div class="log">
    <%= link_to "", destroy_user_session_path, method: :delete, id: "stuff" %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "log_text" %></div>
  <% if not @edit_profile %>
    <div class="profile">
      <% if current_user.profile and not @on_profile %>
        <%= link_to "", profile_path(current_user.profile.id), method: :get, id: "stuff" %>
        <%= link_to "Profile", profile_path(current_user.profile.id), method: :get, :class => "profile_text" %>
      <% elsif current_user.profile and @on_profile%>
        <%= link_to "", edit_profile_path(current_user.profile.id), method: :get, id: "stuff" %>
        <%= link_to "Edit Profile", edit_profile_path(current_user.profile.id), method: :get, :class => "profile_text" %>
      <% else %>
        <%= link_to "", new_profile_path, method: :get, id: "stuff" %>
        <%= link_to "Profile", new_profile_path, method: :get, :class => "profile_text" %>
      <% end %>
    </div>
  <% end %>
<% end %>
<div id="big_container">
  <%= yield %>
</div>



</body>
</html>

app/views/profiles/edit.html.erb
<%= stylesheet_link_tag "form" %>

<div id="topleftbutton">
<%= link_to '', profile_path(current_user.profile.id), id: "back" %>
<%= link_to "Back", profile_path(current_user.profile.id), id: "backtext" %></div> 

<%= form_for @profile do |f| %>
  <div id="error_explanation">
    <% if @profile.errors.any? %>
      <%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being edited:
        <ul>
          <% @profile.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
  <div id="container">
    <div id="country_name">
      <%= f.label "Edit Profile" %><br>
    </div>
    <%= f.text_field :name, id: "box"%>  
    <div id="upload">
    	<%= f.label "Profile Picture" %>
    	<%= f.file_field :photo %>
    </div>
    <div id="submit">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/profiles/new.html.erb
<%= stylesheet_link_tag "form" %>

<%= form_for @profile do |f| %>
  <div id="error_explanation">
    <% if @profile.errors.any? %>
      <%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being saved:
        <ul>
          <% @profile.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
  <div id="container">
    <div id="country_name">
      <%= f.label "New Profile" %><br>
    </div>
    <%= f.text_field :name, id: "box"%>  
    <div id="upload">
    	<%= f.label "Profile Picture" %>
    	<%= f.file_field :photo %>
    </div>
    <div id="submit">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div id="topleftbutton">
<%= link_to '', countries_path, id: "back" %>
<%= link_to "Back", countries_path, id: "backtext" %></div>
<br><br><br><br><br>
<%= @profile.name %>
<br>
<%= image_tag @profile.photo.url(:small) %>